Repository Code-the-Dream-School/ii-practicum-team-7-front, pull requests merged in 2025-05, with the labels that each got.

#19 Scrum 74 set up tailwind
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.jsx
  src/index.css
  tailwind.config.js
  vite.config.js
Labels: Ready for Review, Mentor Reviewed

#18 Job search page
  .gitignore
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/JobSearch.css
  src/components/JobSearch.jsx
  src/components/PageWrapper.jsx
  src/components/jobsearch/JobPostings.jsx
  src/components/jobsearch/JobSearchArea.jsx
  src/components/jobsearch/Pagination.jsx
  src/components/landing/FooterSection.jsx
  src/components/landing/HeroSection.jsx
  src/components/landing/HowSection.jsx
  src/components/landing/Navbar.jsx
  src/components/landing/SignUpSection.jsx
  src/components/landing/TestimonialSection.jsx
  src/images/jobsearch.jpg
  src/index.css
Labels: Ready for Review

#21 SCRUM-24-customers-can-create-jobs-Hannah
  src/App.jsx
  src/components/JobPost.jsx
  src/components/landing/HeroSection.jsx
  src/index.css
Labels: Ready for Review

#22 Set availability
  package-lock.json
  package.json
  src/components/AvailabilityInput.jsx
Labels: Ready for Review

#25 Scrum75 - Add profile and logout buttons to nav bar
  package-lock.json
  src/App.jsx
  src/components/UserProfile/UserProfilePg.jsx
  src/components/landing/Navbar.jsx
Labels: Ready for Review

#24 style-job-pages
  src/components/JobPost.jsx
  src/components/JobSearch.css
  src/components/JobSearch.jsx
  src/components/UserProfile/UserProfilePg.jsx
  src/components/jobsearch/JobPostings.jsx
  src/components/jobsearch/JobSearchArea.jsx
  src/components/jobsearch/Pagination.jsx
  src/components/landing/HowSection.jsx
  src/components/landing/Navbar.jsx
  src/components/landing/SignUpSection.jsx
  src/index.css
  src/routeStyles.js
Labels: Ready for Review

#26 UserProfilePg.jsx and UserInfoForm.jsx update
  src/components/UserProfile/FormFields.jsx
  src/components/UserProfile/UserInfoForm.jsx
  src/components/UserProfile/UserProfilePg.jsx
Labels: Ready for Review

#15 User ratings
  src/App.jsx
  src/components/ReviewForm.jsx
  src/components/ReviewList.jsx
  src/components/ReviewPage.jsx
Labels: Ready for Review, Changes Needed

#16 Email job updates
  src/components/ReviewForm.jsx
  src/components/UserProfile/UserProfilePg.jsx
  src/util/sendJobUpdateEmail.js
Labels: Ready for Review

#30 Job search page - a few additions
  package-lock.json
  package.json
  src/components/JobPost.jsx
  src/components/JobSearch.jsx
  src/components/jobsearch/JobPostings.jsx
Labels: Ready for Review
