Repository Code-the-Dream-School/ii-practicum-team-7-front, pull requests merged in 2025-04, with the labels that each got.

#7 Create pull_request_template.md
  .github/pull_request_template.md
Labels: Mentor Reviewed

#8 Joel user login user registration
  package-lock.json
  package.json
  src/App.jsx
  src/components/LoginForm.jsx
  src/components/RegisterForm.jsx
Labels: Peer Reviewed, Mentor Reviewed

#10 Created user info form
  package-lock.json
  package.json
  src/components/UserInfoForm.jsx
Labels: In progress

#14 Scrum56 user profile anamaria
  package-lock.json
  package.json
  src/App.jsx
  src/components/LoginForm.jsx
  src/components/RegisterForm.jsx
  src/components/UserInfoForm.jsx
  src/components/UserProfile/UserProfilePg.jsx
  src/components/UserProfile/userProfile.module.css
Labels: Ready for Review

#13 react router and header/footer/main
  package-lock.json
  src/App.css
  src/App.jsx
  src/components/PageWrapper.jsx
Labels: Mentor Reviewed, Peer Reviewed

#17 Code editing related to scrum71 Hannah
  src/components/LoginForm.jsx
  src/components/RegisterForm.jsx
  src/components/UserInfoForm.jsx
  src/components/UserProfile/UserProfilePg.jsx
  src/components/landing/Navbar.jsx
Labels: Ready for Review, Mentor Reviewed
